export const plans = [
  {
    title: 'Part-time wingman',
    price: '$1,430',
    unit: '/mo',
    tagline: '30 hrs/week, VOIP included',
    badge: null,
    cta: { label: 'Get Started', href: '#contact', style: 'outline' },
    features: [
      '1 dedicated Towbook-trained VA',
      'Your choice of shift hours',
      'Phone answering via VOIP ext.',
      'Towbook dispatch & data entry',
      'WhatsApp communication',
      'Lien sale support',
    ],
  },
  {
    title: 'Full-time wingman',
    price: '$1,964',
    unit: '/mo',
    tagline: '40 hrs/week, VOIP included',
    badge: 'Most Popular',
    cta: { label: 'Get Started', href: '#contact', style: 'primary' },
    features: [
      '1 dedicated Towbook-trained VA',
      'Standard 5-day office hours',
      'Full dispatch & motor club handling',
      'Towbook data entry & clean-up',
      'Lien sale management',
      'Priority WhatsApp response',
    ],
  },
  {
    title: '24/7 & more than 1 VA',
    price: 'Custom',
    unit: null,
    tagline: 'Still just $11/hr — scaled to your needs',
    badge: null,
    cta: { label: 'Contact Us', href: '#contact', style: 'outline' },
    features: [
      'Multiple dedicated VAs',
      '24/7 around-the-clock coverage',
      'Overlapping shift scheduling',
      'Multi-location tow company support',
      'Dedicated account manager',
      'Volume pricing available',
    ],
  },
]
